changed suggested video dimensions, added cursor as pointer, and impl…
Creatives-Garage/bambakids pull request #20
Opened 2023-09-20 07:48 UTC by henrymutua

…emented responsiveness

2023-09-26 09:11 UTC, bob606 requested changes
See comments and please make sure that all the book pages are functional :rocket:

2023-09-26 09:11 UTC, bob606 commented on src/features/Home/Hero/Hero.module.scss
> +    @media(max-width: 768px){
the margin bottom should actually be styled in the component _(parent)_ which arranges the hero section _(child)_. Which in this  case is `/home/bob/Desktop/bambakids/src/pages/index.tsx`. 
Since you want to keep children as reusable as possible, it is harmful if they define their own natural outer boundaries. Sometime you might want to use the element with a margin-bottom 10px and sometimes with 18px. This becomes impossible when you are defining the styles for the outer bounadiaries in the child component itself.

2023-09-26 09:11 UTC, bob606 commented on src/features/Tazama/VideoCard/VideoCard.tsx
revert this changes pls, they are not necessary

2023-09-26 09:11 UTC, bob606 commented on src/features/Tazama/VideoPlayer/videoPlayer.module.scss
the videoplayer height seems to be glitchy on my device. it's not 100% matching the surrounding container.

2023-09-26 09:11 UTC, bob606 commented on src/pages/tazama/videoId.module.scss
the wrapper and the video are still not the same height, despite the changes

2023-09-26 09:11 UTC, bob606 commented on src/shared/Nav/Nav.module.scss
nav design is supposed to be changed according to design screens. especially the search abr is not supposed to be more down then the other elements

2023-09-27 04:22 UTC, zidanegimiga commented
Push what you have and proceed from there

2023-10-18 13:10 UTC, zidanegimiga approved these changes

2023-10-18 13:10 UTC, merged